### ISSUE TITLE
[Bug]: TypeError: animatedIndex.get is not a function (it is undefined)

### ISSUE THREAD

**Issue by mantu-bit** [gorhom/react-native-scroll-bottom-sheet#2360]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

Android

### What happened?

After updating the gorhum bottom sheet to v5.1.6 this error is coming

### Reproduction steps

- Just update the package and you will get this error as soon as you open the bottom sheet modal

### Reproduction sample

N/A

### Relevant log output

```shell
ERROR  TypeError: animatedIndex.get is not a function (it is undefined)

This error is located at:
    in BottomSheetBodyComponent (created by BottomSheet)
    in RCTView (created by View)
    in View (created by BottomSheetHostingContainerComponent)
    in BottomSheetHostingContainerComponent (created by BottomSheet)
    in BottomSheetGestureHandlersProvider (created by BottomSheet)
    in BottomSheet (created by BottomSheet)
    in PortalHostComponent (created by PortalProviderComponent)
    in PortalProviderComponent (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
```
